### PR TITLE
Make Julia executable or kernel a Tool Specification setting

### PR DESCRIPTION
**Pull request by PekkaSavolainen**
This PR makes Julia Tool specs consistent with Python Tool specs. You can now select Basic Console or Jupyter Console execution for each Julia Tool spec separately. The Julia settings on the *Tools* page in *File->Settings* are used as the default execution settings for **new** Julia Tool specs. Then you can set the path to Julia executable, Julia project and/or Julia kernel from the Tool Specification Editor. 

Fixes spine-tools/Spine-Toolbox#1498

Testing:
If you want to test this, **make a copy of the projects you want to test in this branch.** When switching back to `0.8-dev` branch, the projects you have opened in the feature branch probably won't work there anymore, and you need to manually fix the project's local settings json file.

## Checklist before merging
- [x] Documentation (also in Toolbox repo) is up-to-date
- [x] Release notes in Toolbox repo have been updated
- [x] Unit tests have been added/updated accordingly
- [x] Code has been formatted by black
- [x] Unit tests pass

### CODE REVIEW

**Comment by manuelma** [comment]
Sorry I haven't found the time to test this one. I'd suggest we merge since 0.8 is a dev branch anyways? I will definitly test it with SpineOpt at some point, so that should be covered.

**Comment by PekkaSavolainen** [comment]
> Sorry I haven't found the time to test this one. I'd suggest we merge since 0.8 is a dev branch anyways? I will definitly test it with SpineOpt at some point, so that should be covered.

That's fine because I just realized that I need to change this up a little bit. I think I need to set the selected Sysimage as a Tool Specification setting, instead of it being a Tool setting. This means that the sysimage line edit will be removed from Tool properties and inserted into the Tool Specification Editor. This way Julia Executable, project, and sysimage are all Tool Specification Settings. I think it would be quite confusing if Julia executable and project are Tool spec settings, and sysimage is a Tool setting. In addition, at the moment, there is no way to use a sysimage in a Julia Jupyter Console. Using a sysimage in the Jupyter Console requires that there's a --sysimage=<somepath> argument is in the kernel's `kernel.json` file. So, what I also need to do is to add a sysimage line edit into the Julia section of Settings->Tool widget. That way, users can make a Julia kernel with a specific Julia executable, project, and sysimage by clicking the `Make Julia Kernel` button in the Settings widget.

**Comment by soininen** [comment]
> I think I need to set the selected Sysimage as a Tool Specification setting, instead of it being a Tool setting.

Excuse my ignorance of all things Julia, but are sysimages not created by users for their specific environment? If that is the case, then the sysimage setting should not be a Tool specification setting but a Tool setting and its value stored in the local directory. If sysimages are something the tool providers distribute e.g. with SpineOpt plugin, then of course the situation is different and they should be set up in the specification.

**Comment by soininen** [comment]
> This way Julia Executable, project, and sysimage are all Tool Specification Settings.

Please make sure that at least Julia executable and sysimage (perhaps Julia project as well) are stored in specification local data as they are user-specific settings.

**Comment by manuelma** [comment]
> I think I need to set the selected Sysimage as a Tool Specification setting

Thank you @PekkaSavolainen - about the above - you might be right and that might be the way to go. Just sharing the original thought process that led me to make the sysimage a tool setting and not a than a tool spec setting - images can be highly specialized for certain tools. For example, two different SpineOpt tools might hit very different lines of SpineOpt source code depending on the input data. The way it is done now, the sysimage is created by running the tool with its input data and collecting the precompilation statements for that run. That means the sysimage will be adapted to both that tool *and* the input data store. The same sysimage might not be that efficient if applied to a different instance of the same tool, that has a different input data store.

**Comment by PekkaSavolainen** [comment]
> ...The way it is done now, the sysimage is created by running the tool with its input data and collecting the precompilation statements for that run. That means the sysimage will be adapted to both that tool and the input data store. The same sysimage might not be that efficient if applied to a different instance of the same tool, that has a different input data store.

Thanks for the explanation. I was wondering if this might be the reason why the sysimage creation process requires the SpineToolboxProject of the Tool. Here's the current plan:

A quick question, In Julia REPL, how do I know if my sysimage is enabled?

**Comment by manuelma** [comment]
> A quick question, In Julia REPL, how do I know if my sysimage is enabled?

I'm not sure, maybe there is something about it in the documentation. You need to start julia with --sysimage="path to sysimage  file" to use the sysimage, so you would know the sysimage is active if you are a human activating it. Programmatically I don't know.

**Comment by PekkaSavolainen** [comment]
Looks like there's no need to change the selected sysimage as a Tool Spec setting after all. It can stay as a Tool setting where it belongs. I think I managed to enable running Jupyter Consoles with the selected sysimage without the need to create a new kernel for each sysimage. In addition, there was a bug in creating a sysimage when a Julia Tool Spec using the Jupyter Console was selected. It should be fixed now.

**Pull request merged**
